name: Scheduled Task Runner

# 设置触发条件
on:
  # 每天定时触发四次 (北京时间：23:30, 06:00, 12:30, 19:00)
  schedule:
    # Cron 表达式基于 UTC 时间: (分 时 日 月 周)
    # 15:30 UTC -> 23:30 北京时间
    # 22:00 UTC -> 06:00 北京时间
    # 04:30 UTC -> 12:30 北京时间
    # 11:00 UTC -> 19:00 北京时间
    - cron: '30 15,22,4,11 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. 运行脚本
      # 由于脚本是无限循环，在 Actions 环境中它会一直运行直到超时或任务结束。
      # GitHub Actions 默认最长运行时间约为 6 小时。
      # 如果需要精确控制运行时间，可以修改脚本，但通常不必，因为下次定时会重新启动。
      - name: Run Python Script
        # 请根据你实际的脚本文件名进行修改
        run: python task_runner.py
